try to add coverage percentage

diff --git a/.github/workflows/ci_cd_wf.yml b/.github/workflows/ci_cd_wf.yml
--- a/.github/workflows/ci_cd_wf.yml
+++ b/.github/workflows/ci_cd_wf.yml
@@ -1,6 +1,6 @@
 name: test
 
-permissions: write-all
+permissions: write-all 
 
 on:
   push:
@@ -17,7 +17,7 @@ jobs:
     steps:
       - name: Check out repo code
         uses: actions/checkout@v3
-
+      
       - name: Setup Python
         uses: actions/setup-python@v3
         with:
@@ -26,32 +26,20 @@ jobs:
       - name: Install Dependencies
         run: |
           python -m pip install -r requirements.txt
-      - name: Run tests
-        run: |
-          python -m pytest -v tests
-
+      
       - name: Build coverage file
         run: |
           python -m pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=app tests/ | tee pytest-coverage.txt
-
-      - name: Pytest coverage comment
+  
+      - name: Comment coverage on PR
         uses: MishaKav/pytest-coverage-comment@main
         with:
           pytest-coverage-path: ./pytest-coverage.txt
           junitxml-path: ./pytest.xml
 
-      - name: Check the output coverage
+      - name: Check test results and mark workflow as failed if necessary
         run: |
-          echo "Coverage Percantage - ${{ steps.coverageComment.outputs.coverage }}"
-          echo "Coverage Color - ${{ steps.coverageComment.outputs.color }}"
-          echo "Coverage Html - ${{ steps.coverageComment.outputs.coverageHtml }}"
-          echo "Summary Report - ${{ steps.coverageComment.outputs.summaryReport }}"
-
-          echo "Coverage Warnings - ${{ steps.coverageComment.outputs.warnings }}"
-
-          echo "Coverage Errors - ${{ steps.coverageComment.outputs.errors }}"
-          echo "Coverage Failures - ${{ steps.coverageComment.outputs.failures }}"
-          echo "Coverage Skipped - ${{ steps.coverageComment.outputs.skipped }}"
-          echo "Coverage Tests - ${{ steps.coverageComment.outputs.tests }}"
-          echo "Coverage Time - ${{ steps.coverageComment.outputs.time }}"
-          echo "Not Success Test Info - ${{ steps.coverageComment.outputs.notSuccessTestInfo }}"
+          if grep -q 'FAILED' pytest-coverage.txt; then
+            echo 'Test case failed. Marking workflow as failed.'
+            exit 1
+          fi
